### ISSUE TITLE
Munson fails if configure not called

### ISSUE THREAD

**Issue by mwpastore** [stacksocial/munson#12]
Munson fails with the following error if Munson.configure was not called before a fetch:

```ruby
TypeError: can't clone NilClass
    /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/munson-0.3.1/lib/munson/client.rb:36:in `clone'
    /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/munson-0.3.1/lib/munson/client.rb:36:in `connection'
    /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/munson-0.3.1/lib/munson/client.rb:23:in `agent'
    /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/munson-0.3.1/lib/munson/query.rb:22:in `fetch'
    /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/munson-0.3.1/lib/munson/resource.rb:183:in `fetch'
```

Can we detect if configure was not called prior to a resource action and either display a better error or call configure and take the defaults?

**Comment by mwpastore** [comment]
Moved to coryodaniel/munson#1
