### ISSUE TITLE
Munson::Resource#save fails if no attributes defined

### ISSUE THREAD

**Issue by mwpastore** [stacksocial/munson#15]
I'm trying to POST to a collection to add an entry and I'd like to just send an empty attributes hash for the time being for testing purposes. In other words, I don't have any attributes defined on my Munson::Resource. 

For example:

```ruby
post = Post.new
post.save
```

Fails with the following error message:

```ruby
NoMethodError: undefined method `[]' for nil:NilClass
    /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/munson-0.3.1/lib/munson/document.rb:9:in `initialize'
    /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/munson-0.3.1/lib/munson/document.rb:75:in `new'
    /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/munson-0.3.1/lib/munson/document.rb:75:in `save'
    /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/munson-0.3.1/lib/munson/resource.rb:48:in `save'
```

**Comment by mwpastore** [comment]
Moved to coryodaniel/munson#5
